### ISSUE TITLE
Incorrect version reported by `--version`

### ISSUE THREAD

**Issue by fosskers** [gnikit/fortls#117]
**Describe the bug**

The `--version` flag exists but reports the incorrect version.

**To Reproduce**

1. Run `fortls --version`
2. See `0.0.0`.

**Expected behavior**

I should see `2.5.0`.

**Comment by gnikit** [comment]
Thanks for the report @fosskers I seem to be unable to replicate the issue. Have you tried uninstalling `fortls`, deleting the `pip` cache (in Linux under ~/.cache/pip) and then reinstalling?

**Comment by fosskers** [comment]
I'm installing it via [this AUR package](https://aur.archlinux.org/packages/fortls), which invokes [this build script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fortls#n23). Do you see anything wrong there that might screw up the version?

**Comment by gnikit** [comment]
So this is because the dependencies you have listed are incorrect, see https://github.com/gnikit/fortls/blob/435223c4cfae73c8197a2b9842f2ac13b4543b51/pyproject.toml#L2-L7 .

Having said that, **I would strongly recommend against using a package manager like AUR, APT, etc. to install `fortls`!**.
`fortls` runs an autoupdate function in the background, like most language servers to always use the latest version. This inevitably means that it will not be updated through AUR but through PyPi, leading into a version mismatch between AUR and the installed fortls, which I suspect can cause all sorts of issues.

If people want to install through AUR I would just point them to the installation [instructions](https://gnikit.github.io/fortls/quickstart.html#download) (it's 1 command after all).

If you want a package environment that does not use PyPi, see our [conda-forge recipe](https://anaconda.org/conda-forge/fortls) which does not perform the autoupdate.

**Comment by fosskers** [comment]
Thanks. I'm still keen to keep my system package manager "in the loop" and avoid having tools update themselves, so I'll look into the conda recipe.
