### ISSUE TITLE
no autocomplete in use statement for nested modules.

### ISSUE THREAD

**Issue by JHenneberg** [gnikit/fortls#151]
Sometimes I am using a module simply to collect several modules together to be able to use only one use statement instead of several. Unfortunately there is no autocomplete in use statement for nested modules. 

```f90
program main
  use some_mod, only: a_subroutine ! list of available subroutines is provided as expected
  use collection_mod, only: a_subroutine ! list of available subroutines is empty
  implicit none

end program main

module collection_mod

  use some_mod

end module collection_mod

module some_mod
  implicit none

  private
  public :: a_subroutine

contains

  subroutine a_subroutine(x)
    implicit none

    integer, intent(in) :: x

    write(*,*) 'x = ', x
  end subroutine a_subroutine

end module some_mod
```

**Comment by gnikit** [comment]
I will have a look, my first guess is that it's a bug somewhere in https://github.com/gnikit/fortls/blob/52fa2d067820cddea4ec01879ffbff5c971535d5/fortls/objects.py#L119

**Comment by gnikit** [comment]
I can't replicate this issue with v2.9.0. 

![ezgif com-gif-maker](https://user-images.githubusercontent.com/16143716/174874171-f3000a89-232a-431d-af9e-557a4a61d7cc.gif)

Autocomplete does not provide any results when you haven't started typing. I recall having to do this for performance reasons since returning a list of 10k+ entries made it hard to work on big codebases.

**Comment by JHenneberg** [comment]
Sry for wasting your time. I retested it again and it works also in my original codebase.
