### ISSUE TITLE
automatic update process broken under windows 11

### ISSUE THREAD

**Issue by JHenneberg** [gnikit/fortls#163]
**Describe the bug**
Once a new version is released and due to a start of VSCode an update is triggered, the installation fails.

**To Reproduce**
1. Install older version of current one.
2. Start VSCode to trigger automatic update process
![image](https://user-images.githubusercontent.com/6606609/177272193-601d9683-8837-4140-8497-2adf61fbf63b.png)

3. Restart VSCode
![image](https://user-images.githubusercontent.com/6606609/177272269-55ab9c51-a8eb-4a74-90a5-e0e7b3d7f959.png)
4. Check `c:\Users\<USER>\AppData\Local\Programs\Python\Python310\Lib\site-packages\` folder: There are now two folders named:
`~ortls-2.10.0.dist-info ` and `~ortls `. There is no `fortls` folder 

By executing `pip install fortls` the installation of the current version is performed correclty. Just the leftover folder are still there and have to be deinstalled manually.

When still on 2.10 and `pip install fortls --upgrade` is exectued manually there are no ghostfolders and the 2.11 is installed.

**Expected behavior**
Normal update process

**Setup information (please complete the following information):**
 - OS: Windows 11
 - Python Version: 3.10
 - fortls Version 2.10/2.11
 - Code editor used: VSCode

**Comment by gnikit** [comment]
I don't think the automatic update process is broken since there is a unit which still passes on Windows.

From the looks of it there is something else wrong, most likely your options, which causes this.

Can you post the channel logs from vscode along with your Fortran settings.

**Comment by JHenneberg** [comment]
The error msg is indicating that smth is wrong with the settings, but installing the newest version like I mentioned or updating manually works fine. The message is not appearing.
The only setting that I have for `fortls` is `"fortran.fortls.notifyInit": true,`

**Comment by gnikit** [comment]
I think there is something funny going on with Windows 11 and the file permissions. My uneducated guess is that Windows puts a lock on folders that have running processes thus not allowing VS Code spawned pip to run and update like it is supposed to.

I don't think it's `pip` itself, I gave it a go on Linux but you can try it yourself on Windows. 
- Add the `--disable_autoupdate` flag to fortls so as to not update upon initialisation.
- Open a Fortran project for fortls to spawn and initialise
- Open a terminal and run `python -m pip install --user --upgrade fortls -y` (python being the location of your Python dist)

That should run to completion and when restarting `fortls` via the command palette `Fortran: Restart the Fortran Language Server` the log channel should report the new version.

As a last effort you can attempt to upgrade your pip installation 

```sh
python -m pip install --upgrade pip
```

If it is Windows itself (or anything else that is close to OS level) it won't be possible to fix, since it would require `fortls` to interact with the underlying OS in ways that are "unacceptable" for a lot of the users, change file permissions, stop and restart tasks, etc.

**Comment by gnikit** [comment]
> Not sure if --user is the solution because installing it myself via commandline is working fine without being in admin mode.

`--user` is used for portability. In older versions of `pip` attempting to install packages in a places where you don't have permissions would fail, newer versions of `pip` will retry to install with the `--user` flag.

**Comment by JHenneberg** [comment]
despite `-y` is not recognized it works (`python -m pip install --user --upgrade fortls`). I retested agains `python -m pip install fortls --upgrade` which fails.

**Comment by gnikit** [comment]
Apologies, the `-y` was a mistake.

The `--user` results make sense, that is what Modern Fortran runs in the terminal
https://github.com/fortran-lang/vscode-fortran-support/blob/8fab0851e4cf6be08f7bacc73699874b9818ee7f/src/lib/tools.ts#L148

So I am not sure I get what is going on. Did you try and update your `pip` version?

**Comment by gnikit** [comment]
Oh damn, I missed something! This is how fortls upgrades
https://github.com/gnikit/fortls/blob/4f17ee40647f27fbe9cc93fd1ff2b3314b866b40/fortls/langserver.py#L1759-L1767
which as you can see does not use `--user`. No idea how I missed that. Let me issue a release now.
