### ISSUE TITLE
Feature request:  documentHighlightProvider support

### ISSUE THREAD

**Issue by nujabse** [gnikit/fortls#43]
Currently `fortls` does not implement the documentHighlightProvider language server feature, which makes emacs `lsp-mode` do not have symbol highlighting feature. Can you implement this feature ?

**Comment by gnikit** [comment]
Could you please elaborate a bit about what you mean by "symbol highlighting feature"? From what I understand `documentHighlightProvider` should be nearly identical to `textDocument/references` which is already implemented.
If by any chance you mean syntax highlighting, that is usually provided by the extension and not the language server since it is a big task of its own.

>Document Highlights Request (:leftwards_arrow_with_hook:)
The document highlight request is sent from the client to the server to resolve a document highlights for a given text document position. For programming languages this usually highlights all references to the symbol scoped to this file. However we kept ‘textDocument/documentHighlight’ and ‘textDocument/references’ separate requests since the first one is allowed to be more fuzzy. Symbol matches usually have a [DocumentHighlightKind](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#documentHighlightKind) of Read or Write whereas fuzzy or textual matches use Textas the kind.

see: https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocument_documentHighlight

**Comment by gnikit** [comment]
Further elaborating on my previous comments, this is the current status of the reference highlighting, which I suspect is what you are asking

![image](https://user-images.githubusercontent.com/16143716/152478855-3c561175-f6c7-471a-a7cb-e0016552f1b8.png)

Could you please post the settings you use for `fortls`?

**Comment by nujabse** [comment]
Yes, what I mean by "symbol highlighting" is *reference highlighting*, see the example code in Emacs using `fortls` with `lsp-mode`:
![image](https://user-images.githubusercontent.com/9455367/152490011-9cd12482-4a51-483d-8041-7eaf537c8952.png)
The `dist` variables under the curser should have been highlighted, but I can not get it working in Emacs with `lsp-mode`. However, reference highlighting using`fortls` works just fine in Vscode. 
The settings for `fortls` I'm using are `"--variable_hover" "--hover_signature" "--lowercase_intrinsics" `

**Comment by gnikit** [comment]
So I would guess then that `lsp-mode` does not support `textDocument/references`, which is weird. Has that always been the case? Your client should be able to handle both `textDocument/references` and `documentHighlightProvider`.

**Comment by nujabse** [comment]
Well, it seems that `lsp-mode` needs `documentHighlightProvider` to do the reference highlighting, as discussed in the [issue](https://github.com/emacs-lsp/lsp-mode/issues/3338#issue-1122602616). Maybe I just need to wait for `lsp-mode` to support it. Thanks anyway for your help! `fortls` is very useful.

**Comment by gnikit** [comment]
I don't think there is any harm registering both `references` and `documentHighlight`.

**Comment by rcoacci** [comment]
Hi, after some time struggling with this problem, I discovered that you missed adding `"documentHighlightProvider": True` to the `server_capabilities` dictionary in langserver.py::serve_initialize. Without it, LSP clients don't request the documentHighlight and the symbol highlight doesn't work. After adding it in a local copy Emacs' lsp-mode does symbol highlight correctly.
