### ISSUE TITLE
Visual Studio 2022 Support

### ISSUE THREAD

**Issue by M-Kuzovic** [gnikit/fortls#66]
Fortran language server currently does not have an extension for Visual Studio 2022.

Update Visual Studio extension to work on Visual Studio 2022 and publish it to VS marketplace.

**Comment by gnikit** [comment]
Hi @M-Kuzovic this repo is responsible only for implementing the Language Server Protocol (LSP) for Fortran and not the integration of the server to the editor, for that you need an extension. Given that support for Fortran in VS used to be (not sure if it is still the case) offered by Intel through proprietary and paid compilers and extensions, the incentive to develop a free open source extension for a product that is monetised, as you can imagine, is quite low.

Please keep in mind that we develop these tools in our free time and release them under open-source licenses for all to use. That simply means that, other than the joy of contributing to the Fortran community, there is no compensation for our time spent developing these tools. On the other hand, Microsoft, Intel and other Fortran compiler authors have paid software engineers for these tasks. 

It might be worth filling a feature request with the VS team. They only need to implement the client side of the LSP, since the server is implemented in this repo.

For the aforementioned reasons I will be closing this issue.
