### ISSUE TITLE
Internal version in conda-forge distribution

### ISSUE THREAD

**Issue by gbogopolsky** [gnikit/fortls#73]
I noticed that while the package version is correctly given by conda/mamba (`fortls                    2.2.5            py39h6e9494a_1    conda-forge`), `fortls --version` yields the wrong version number (`0.0.0`) whereas the PyPi versions does not (`2.5.5`).

**Comment by gnikit** [comment]
I think both pypi and conda-forge should have the same version, since conda-forge pulls from pypi and not GitHub. 

About the version output, I will look into it. If it's broken I will probably have to contact the conda-forge team because the version semantics should be already in the files that conda-forge receives from pypi.

**Comment by gbogopolsky** [comment]
Makes sense to me. I am not sure if it is an issue, but I just wanted to notify you.

**Comment by gnikit** [comment]
It's absolutely an issue and your timing couldn't have been better. I was just about to role out a feature where fortls attempts to autoupdate if the local version is smaller than the remote version on pypi.

It would be a real pain if conda-forge does not store the right version semantics since it would lead to a message popping up every time fortls starts.

**Comment by gbogopolsky** [comment]
I just noticed that open issue too. That should be very helpful to maintain `fortls` up-to-date, instead of manually doing it. 
So thank you, and you're welcome.

**Comment by gnikit** [comment]
Hey @gbogopolsky, I spent a solid hour trying to figure out what's happening. The short summary is that conda-forge packages `fortls` from PyPi, for some reason unbeknownst to me, as `fortls-0.0.0.dist-info` completely ignoring the version files. `importlib`, which is how we get our version, reads the name of that file and when `version(__package__)` is called it thinks that our version is 0.0.0 instead of 2.2.5, even though there is a file called `_version.py` that holds the correct version info.

This is not a major issue, since with the autoupdate feature I am about to roll out,  we call pip directly (pip is always present in modern python distros) and the correct `*-info` file is created. Still annoying but we should be okay.
You can fix it yourself by running `python -m pip install fortls --upgrade` and the version of conda-forge should now be matching.

FYI I would not recommend to anyone using the conda-forge installation, hence why I kept it outside the docs. The only reason why I even bothered creating the conda-forge recipe is for some very unique circumstances where you would need to ship a venv with anaconda and no PyPi.

**Comment by gnikit** [comment]
I will be closing this issue now. Hopefully all works.

**Comment by gbogopolsky** [comment]
Thanks for the explanation and the precisions, and very nice work once again!

**Comment by bilderbuchi** [comment]
Re the problem with the conda packaging, I noticed that your recipe'S [host section](https://github.com/conda-forge/fortls-feedstock/blob/master/recipe/meta.yaml#L20) does not have `setuptools_scm` - don't you need that? I found tox-conda which uses the same [mechanism](https://github.com/tox-dev/tox-conda/blob/master/pyproject.toml#L10) as you do, and [has that entry](https://github.com/conda-forge/tox-conda-feedstock/blob/master/recipe/meta.yaml#L23).

**Comment by gnikit** [comment]
Nice catch @bilderbuchi I will add that in the recipe tonight.

**Comment by gnikit** [comment]
@bilderbuchi and @gbogopolsky This should now be fixed build ending with number `_2` should be available for download see: https://anaconda.org/conda-forge/fortls/files
